<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>pps</AssemblyName>
    <RootNamespace>PowerPlanSwitcher.Cli</RootNamespace>
    <PlatformTarget>x64</PlatformTarget>
    <Platforms>x64</Platforms>
    <Description>Command-line interface for PowerPlanSwitcher</Description>
    <Authors>Sebastian Becker</Authors>
    <Company>Sebastian Becker</Company>
    <Product>PowerPlanSwitcher</Product>
    <VersionPrefix>1.2.10</VersionPrefix>
    <VersionSuffix>rc2</VersionSuffix>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PowerManagement\PowerManagement.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.0" />
  </ItemGroup>

</Project>
